/**
 * VCopying.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager.algorithms;

public class VCopying extends com.objectspace.voyager.VObject
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.algorithms.Copying" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "copy(Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.OutputIterator;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "copy(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.OutputIterator;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "copy(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.Container;)V" );
  private static final com.objectspace.voyager.util.Token __class3 = new com.objectspace.voyager.util.Token( "copyBackward(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;)Lcom.objectspace.jgl.OutputIterator;" );
  
  static
    {
    __register( new VCopying() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VCopying that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VCopying()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.algorithms.Copying";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VCopying and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VCopying( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copy( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copy( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) copy( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copy( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copy( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copy( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) copy( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copy( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copy( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    copy( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void copy( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    copy( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copyBackward( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BidirectionalIterator arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class3, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result copyBackward( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BidirectionalIterator arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copyBackward( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copyBackward( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BidirectionalIterator arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) copyBackward( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator copyBackward( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BidirectionalIterator arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return copyBackward( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  }
