/**
 * VHeap.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager.algorithms;

public class VHeap extends com.objectspace.voyager.VObject
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.algorithms.Heap" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "pushHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;)V" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "pushHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BinaryPredicate;)V" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "popHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;)V" );
  private static final com.objectspace.voyager.util.Token __class3 = new com.objectspace.voyager.util.Token( "popHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BinaryPredicate;)V" );
  private static final com.objectspace.voyager.util.Token __class4 = new com.objectspace.voyager.util.Token( "makeHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;)V" );
  private static final com.objectspace.voyager.util.Token __class5 = new com.objectspace.voyager.util.Token( "makeHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BinaryPredicate;)V" );
  private static final com.objectspace.voyager.util.Token __class6 = new com.objectspace.voyager.util.Token( "sortHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;)V" );
  private static final com.objectspace.voyager.util.Token __class7 = new com.objectspace.voyager.util.Token( "sortHeap(Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BidirectionalIterator;Lcom.objectspace.jgl.BinaryPredicate;)V" );
  
  static
    {
    __register( new VHeap() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VHeap that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VHeap()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.algorithms.Heap";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VHeap and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VHeap( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return pushHeap( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    pushHeap( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    pushHeap( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return pushHeap( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    pushHeap( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void pushHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    pushHeap( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return popHeap( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    popHeap( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    popHeap( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class3, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return popHeap( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    popHeap( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void popHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    popHeap( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class4, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return makeHeap( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    makeHeap( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    makeHeap( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class5, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return makeHeap( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    makeHeap( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void makeHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    makeHeap( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class6, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return sortHeap( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    sortHeap( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    sortHeap( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class7, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return sortHeap( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    sortHeap( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void sortHeap( com.objectspace.jgl.BidirectionalIterator arg1, com.objectspace.jgl.BidirectionalIterator arg2, com.objectspace.jgl.BinaryPredicate arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    sortHeap( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  }
