/**
 * VTransforming.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager.algorithms;

public class VTransforming extends com.objectspace.voyager.VObject
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.algorithms.Transforming" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.OutputIterator;Lcom.objectspace.jgl.UnaryFunction;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.OutputIterator;Lcom.objectspace.jgl.UnaryFunction;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.UnaryFunction;)V" );
  private static final com.objectspace.voyager.util.Token __class3 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.OutputIterator;Lcom.objectspace.jgl.BinaryFunction;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class4 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.OutputIterator;Lcom.objectspace.jgl.BinaryFunction;)Lcom.objectspace.jgl.OutputIterator;" );
  private static final com.objectspace.voyager.util.Token __class5 = new com.objectspace.voyager.util.Token( "transform(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.BinaryFunction;)V" );
  private static final com.objectspace.voyager.util.Token __class6 = new com.objectspace.voyager.util.Token( "collect(Lcom.objectspace.jgl.ForwardIterator;Lcom.objectspace.jgl.ForwardIterator;Lcom.objectspace.jgl.UnaryFunction;)Lcom.objectspace.jgl.Container;" );
  private static final com.objectspace.voyager.util.Token __class7 = new com.objectspace.voyager.util.Token( "collect(Lcom.objectspace.jgl.Container;Lcom.objectspace.jgl.UnaryFunction;)Lcom.objectspace.jgl.Container;" );
  
  static
    {
    __register( new VTransforming() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VTransforming that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VTransforming()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.algorithms.Transforming";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VTransforming and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VTransforming( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.UnaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __staticMethod( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.UnaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.UnaryFunction arg4, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) transform( arg1, arg2, arg3, arg4, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.UnaryFunction arg4, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.jgl.UnaryFunction arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) transform( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.OutputIterator arg2, com.objectspace.jgl.UnaryFunction arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.UnaryFunction arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    transform( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.UnaryFunction arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    transform( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3, com.objectspace.jgl.OutputIterator arg4, com.objectspace.jgl.BinaryFunction arg5, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    __messenger.writeObject( arg5 );
    return __staticMethod( __address, __classname, __messenger, __class3, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3, com.objectspace.jgl.OutputIterator arg4, com.objectspace.jgl.BinaryFunction arg5, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, arg5, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3, com.objectspace.jgl.OutputIterator arg4, com.objectspace.jgl.BinaryFunction arg5, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) transform( arg1, arg2, arg3, arg4, arg5, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.InputIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3, com.objectspace.jgl.OutputIterator arg4, com.objectspace.jgl.BinaryFunction arg5, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, arg5, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.BinaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __staticMethod( __address, __classname, __messenger, __class4, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.BinaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.BinaryFunction arg4, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.OutputIterator) transform( arg1, arg2, arg3, arg4, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.OutputIterator transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.OutputIterator arg3, com.objectspace.jgl.BinaryFunction arg4, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.Container arg3, com.objectspace.jgl.BinaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __staticMethod( __address, __classname, __messenger, __class5, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.Container arg3, com.objectspace.jgl.BinaryFunction arg4, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return transform( arg1, arg2, arg3, arg4, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.Container arg3, com.objectspace.jgl.BinaryFunction arg4, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    transform( arg1, arg2, arg3, arg4, __newStaticDefaultMessenger(), __address, __timeout ).rethrowException();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static void transform( com.objectspace.jgl.Container arg1, com.objectspace.jgl.Container arg2, com.objectspace.jgl.Container arg3, com.objectspace.jgl.BinaryFunction arg4, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    transform( arg1, arg2, arg3, arg4, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result collect( com.objectspace.jgl.ForwardIterator arg1, com.objectspace.jgl.ForwardIterator arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __staticMethod( __address, __classname, __messenger, __class6, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result collect( com.objectspace.jgl.ForwardIterator arg1, com.objectspace.jgl.ForwardIterator arg2, com.objectspace.jgl.UnaryFunction arg3, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return collect( arg1, arg2, arg3, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.Container collect( com.objectspace.jgl.ForwardIterator arg1, com.objectspace.jgl.ForwardIterator arg2, com.objectspace.jgl.UnaryFunction arg3, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.Container) collect( arg1, arg2, arg3, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.Container collect( com.objectspace.jgl.ForwardIterator arg1, com.objectspace.jgl.ForwardIterator arg2, com.objectspace.jgl.UnaryFunction arg3, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return collect( arg1, arg2, arg3, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result collect( com.objectspace.jgl.Container arg1, com.objectspace.jgl.UnaryFunction arg2, com.objectspace.voyager.message.Messenger __messenger, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __staticMethod( __address, __classname, __messenger, __class7, __timeout );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method.
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.voyager.message.Result collect( com.objectspace.jgl.Container arg1, com.objectspace.jgl.UnaryFunction arg2, com.objectspace.voyager.message.Messenger __messenger, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return collect( arg1, arg2, __messenger, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @param __timeout The timeout valie in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.Container collect( com.objectspace.jgl.Container arg1, com.objectspace.jgl.UnaryFunction arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    return (com.objectspace.jgl.Container) collect( arg1, arg2, __newStaticDefaultMessenger(), __address, __timeout ).readObject();
    }
  
    /**
   * @param __address The address of the program that contains the class.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public static com.objectspace.jgl.Container collect( com.objectspace.jgl.Container arg1, com.objectspace.jgl.UnaryFunction arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    return collect( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  }
