/**
 * VOrderedMap.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager;

public class VOrderedMap extends VMap
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.OrderedMap" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "<init>()" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "<init>(Z)" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "<init>(Lcom.objectspace.jgl.BinaryPredicate;)" );
  private static final com.objectspace.voyager.util.Token __class3 = new com.objectspace.voyager.util.Token( "<init>(Lcom.objectspace.jgl.BinaryPredicate;Z)" );
  private static final com.objectspace.voyager.util.Token __class4 = new com.objectspace.voyager.util.Token( "<init>(Lcom.objectspace.jgl.OrderedMap;)" );
  private static final com.objectspace.voyager.util.Token __instance0 = new com.objectspace.voyager.util.Token( "allowsDuplicates()Z" );
  private static final com.objectspace.voyager.util.Token __instance1 = new com.objectspace.voyager.util.Token( "clone()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance2 = new com.objectspace.voyager.util.Token( "copy(Lcom.objectspace.jgl.OrderedMap;)V" );
  private static final com.objectspace.voyager.util.Token __instance3 = new com.objectspace.voyager.util.Token( "toString()Ljava.lang.String;" );
  private static final com.objectspace.voyager.util.Token __instance4 = new com.objectspace.voyager.util.Token( "elements()Ljava.util.Enumeration;" );
  private static final com.objectspace.voyager.util.Token __instance5 = new com.objectspace.voyager.util.Token( "start()Lcom.objectspace.jgl.ForwardIterator;" );
  private static final com.objectspace.voyager.util.Token __instance6 = new com.objectspace.voyager.util.Token( "finish()Lcom.objectspace.jgl.ForwardIterator;" );
  private static final com.objectspace.voyager.util.Token __instance7 = new com.objectspace.voyager.util.Token( "begin()Lcom.objectspace.jgl.OrderedMapIterator;" );
  private static final com.objectspace.voyager.util.Token __instance8 = new com.objectspace.voyager.util.Token( "end()Lcom.objectspace.jgl.OrderedMapIterator;" );
  private static final com.objectspace.voyager.util.Token __instance9 = new com.objectspace.voyager.util.Token( "isEmpty()Z" );
  private static final com.objectspace.voyager.util.Token __instance10 = new com.objectspace.voyager.util.Token( "size()I" );
  private static final com.objectspace.voyager.util.Token __instance11 = new com.objectspace.voyager.util.Token( "maxSize()I" );
  private static final com.objectspace.voyager.util.Token __instance12 = new com.objectspace.voyager.util.Token( "equals(Lcom.objectspace.jgl.OrderedMap;)Z" );
  private static final com.objectspace.voyager.util.Token __instance13 = new com.objectspace.voyager.util.Token( "swap(Lcom.objectspace.jgl.OrderedMap;)V" );
  private static final com.objectspace.voyager.util.Token __instance14 = new com.objectspace.voyager.util.Token( "clear()V" );
  private static final com.objectspace.voyager.util.Token __instance15 = new com.objectspace.voyager.util.Token( "remove(Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance16 = new com.objectspace.voyager.util.Token( "remove(Ljava.lang.Object;I)I" );
  private static final com.objectspace.voyager.util.Token __instance17 = new com.objectspace.voyager.util.Token( "remove(Ljava.util.Enumeration;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance18 = new com.objectspace.voyager.util.Token( "remove(Ljava.util.Enumeration;Ljava.util.Enumeration;)I" );
  private static final com.objectspace.voyager.util.Token __instance19 = new com.objectspace.voyager.util.Token( "find(Ljava.lang.Object;)Lcom.objectspace.jgl.OrderedMapIterator;" );
  private static final com.objectspace.voyager.util.Token __instance20 = new com.objectspace.voyager.util.Token( "count(Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance21 = new com.objectspace.voyager.util.Token( "countValues(Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance22 = new com.objectspace.voyager.util.Token( "lowerBound(Ljava.lang.Object;)Lcom.objectspace.jgl.OrderedMapIterator;" );
  private static final com.objectspace.voyager.util.Token __instance23 = new com.objectspace.voyager.util.Token( "upperBound(Ljava.lang.Object;)Lcom.objectspace.jgl.OrderedMapIterator;" );
  private static final com.objectspace.voyager.util.Token __instance24 = new com.objectspace.voyager.util.Token( "equalRange(Ljava.lang.Object;)Lcom.objectspace.jgl.Range;" );
  private static final com.objectspace.voyager.util.Token __instance25 = new com.objectspace.voyager.util.Token( "getComparator()Lcom.objectspace.jgl.BinaryPredicate;" );
  private static final com.objectspace.voyager.util.Token __instance26 = new com.objectspace.voyager.util.Token( "get(Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance27 = new com.objectspace.voyager.util.Token( "put(Ljava.lang.Object;Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance28 = new com.objectspace.voyager.util.Token( "add(Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance29 = new com.objectspace.voyager.util.Token( "add(Ljava.lang.Object;Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance30 = new com.objectspace.voyager.util.Token( "keys()Ljava.util.Enumeration;" );
  private static final com.objectspace.voyager.util.Token __instance31 = new com.objectspace.voyager.util.Token( "keys(Ljava.lang.Object;)Ljava.util.Enumeration;" );
  private static final com.objectspace.voyager.util.Token __instance32 = new com.objectspace.voyager.util.Token( "values(Ljava.lang.Object;)Ljava.util.Enumeration;" );
  private static final com.objectspace.voyager.util.Token __instance33 = new com.objectspace.voyager.util.Token( "dump()V" );
  
  static
    {
    __register( new VOrderedMap() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VOrderedMap that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VOrderedMap()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.OrderedMap";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VOrderedMap and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __constructor( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( boolean arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeBoolean( arg1 );
    __constructor( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( boolean arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.BinaryPredicate arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __constructor( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.BinaryPredicate arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.BinaryPredicate arg1, boolean arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __messenger.writeBoolean( arg2 );
    __constructor( __address, __classname, __messenger, __class3, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.BinaryPredicate arg1, boolean arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.OrderedMap arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __constructor( __address, __classname, __messenger, __class4, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VOrderedMap( com.objectspace.jgl.OrderedMap arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result allowsDuplicates( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance0 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public boolean allowsDuplicates() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = allowsDuplicates( __newDefaultMessenger() );
    return __result.readBoolean();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result clone( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance1 );
    }
  
  
  public Object clone()
    {
    com.objectspace.voyager.message.Result __result = clone( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result copy( com.objectspace.jgl.OrderedMap arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance2 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void copy( com.objectspace.jgl.OrderedMap arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = copy( arg1, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result toString( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance3 );
    }
  
  
  public String toString()
    {
    com.objectspace.voyager.message.Result __result = toString( __newDefaultMessenger() );
    return (String) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result elements( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance4 );
    }
  
  
  public java.util.Enumeration elements()
    {
    com.objectspace.voyager.message.Result __result = elements( __newDefaultMessenger() );
    return (java.util.Enumeration) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result start( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance5 );
    }
  
  
  public com.objectspace.jgl.ForwardIterator start()
    {
    com.objectspace.voyager.message.Result __result = start( __newDefaultMessenger() );
    return (com.objectspace.jgl.ForwardIterator) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result finish( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance6 );
    }
  
  
  public com.objectspace.jgl.ForwardIterator finish()
    {
    com.objectspace.voyager.message.Result __result = finish( __newDefaultMessenger() );
    return (com.objectspace.jgl.ForwardIterator) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result begin( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance7 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.OrderedMapIterator begin() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = begin( __newDefaultMessenger() );
    return (com.objectspace.jgl.OrderedMapIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result end( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance8 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.OrderedMapIterator end() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = end( __newDefaultMessenger() );
    return (com.objectspace.jgl.OrderedMapIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result isEmpty( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance9 );
    }
  
  
  public boolean isEmpty()
    {
    com.objectspace.voyager.message.Result __result = isEmpty( __newDefaultMessenger() );
    return __result.readBooleanRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result size( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance10 );
    }
  
  
  public int size()
    {
    com.objectspace.voyager.message.Result __result = size( __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result maxSize( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance11 );
    }
  
  
  public int maxSize()
    {
    com.objectspace.voyager.message.Result __result = maxSize( __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result equals( com.objectspace.jgl.OrderedMap arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance12 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public boolean equals( com.objectspace.jgl.OrderedMap arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = equals( arg1, __newDefaultMessenger() );
    return __result.readBoolean();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result swap( com.objectspace.jgl.OrderedMap arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance13 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void swap( com.objectspace.jgl.OrderedMap arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = swap( arg1, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result clear( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance14 );
    }
  
  
  public void clear()
    {
    com.objectspace.voyager.message.Result __result = clear( __newDefaultMessenger() );
    __result.rethrowExceptionRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance15 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public Object remove( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, __newDefaultMessenger() );
    return __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( Object arg1, int arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeInt( arg2 );
    return __instanceMethod( __messenger, __instance16 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int remove( Object arg1, int arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( java.util.Enumeration arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance17 );
    }
  
  
  public Object remove( java.util.Enumeration arg1 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( java.util.Enumeration arg1, java.util.Enumeration arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance18 );
    }
  
  
  public int remove( java.util.Enumeration arg1, java.util.Enumeration arg2 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result find( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance19 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.OrderedMapIterator find( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = find( arg1, __newDefaultMessenger() );
    return (com.objectspace.jgl.OrderedMapIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result count( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance20 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int count( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = count( arg1, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result countValues( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance21 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int countValues( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = countValues( arg1, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result lowerBound( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance22 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.OrderedMapIterator lowerBound( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = lowerBound( arg1, __newDefaultMessenger() );
    return (com.objectspace.jgl.OrderedMapIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result upperBound( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance23 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.OrderedMapIterator upperBound( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = upperBound( arg1, __newDefaultMessenger() );
    return (com.objectspace.jgl.OrderedMapIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result equalRange( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance24 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.Range equalRange( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = equalRange( arg1, __newDefaultMessenger() );
    return (com.objectspace.jgl.Range) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result getComparator( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance25 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.BinaryPredicate getComparator() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = getComparator( __newDefaultMessenger() );
    return (com.objectspace.jgl.BinaryPredicate) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result get( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance26 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public Object get( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = get( arg1, __newDefaultMessenger() );
    return __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result put( Object arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance27 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public Object put( Object arg1, Object arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = put( arg1, arg2, __newDefaultMessenger() );
    return __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result add( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance28 );
    }
  
  
  public Object add( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = add( arg1, __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result add( Object arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance29 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public Object add( Object arg1, Object arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = add( arg1, arg2, __newDefaultMessenger() );
    return __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result keys( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance30 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public java.util.Enumeration keys() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = keys( __newDefaultMessenger() );
    return (java.util.Enumeration) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result keys( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance31 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public java.util.Enumeration keys( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = keys( arg1, __newDefaultMessenger() );
    return (java.util.Enumeration) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result values( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance32 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public java.util.Enumeration values( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = values( arg1, __newDefaultMessenger() );
    return (java.util.Enumeration) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result dump( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance33 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void dump() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = dump( __newDefaultMessenger() );
    __result.rethrowException();
    }
  }
