/**
 * VPair.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager;

public class VPair extends com.objectspace.voyager.VObject
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.Pair" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "<init>(Ljava.lang.Object;Ljava.lang.Object;)" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "<init>()" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "<init>(Lcom.objectspace.jgl.Pair;)" );
  private static final com.objectspace.voyager.util.Token __instance0 = new com.objectspace.voyager.util.Token( "toString()Ljava.lang.String;" );
  private static final com.objectspace.voyager.util.Token __instance1 = new com.objectspace.voyager.util.Token( "equals(Lcom.objectspace.jgl.Pair;)Z" );
  private static final com.objectspace.voyager.util.Token __instance2 = new com.objectspace.voyager.util.Token( "clone()Ljava.lang.Object;" );
  
  static
    {
    __register( new VPair() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VPair that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VPair()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.Pair";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VPair and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( Object arg1, Object arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __constructor( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( Object arg1, Object arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __constructor( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( com.objectspace.jgl.Pair arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __constructor( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VPair( com.objectspace.jgl.Pair arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result toString( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance0 );
    }
  
  
  public String toString()
    {
    com.objectspace.voyager.message.Result __result = toString( __newDefaultMessenger() );
    return (String) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result equals( com.objectspace.jgl.Pair arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance1 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public boolean equals( com.objectspace.jgl.Pair arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = equals( arg1, __newDefaultMessenger() );
    return __result.readBoolean();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result clone( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance2 );
    }
  
  
  public Object clone()
    {
    com.objectspace.voyager.message.Result __result = clone( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  }
