/**
 * VSList.java
 * <p>
 * @version 1.0
 * @author generated by the objectspace voyager vcc 2.0 beta 1 utility.
 */

package com.objectspace.jgl.voyager;

public class VSList extends com.objectspace.voyager.VObject implements com.objectspace.jgl.Sequence
  {
  private static final com.objectspace.voyager.util.Token __classname = new com.objectspace.voyager.util.Token( "com.objectspace.jgl.SList" );
  private static final com.objectspace.voyager.util.Token __class0 = new com.objectspace.voyager.util.Token( "<init>()" );
  private static final com.objectspace.voyager.util.Token __class1 = new com.objectspace.voyager.util.Token( "<init>(I)" );
  private static final com.objectspace.voyager.util.Token __class2 = new com.objectspace.voyager.util.Token( "<init>(ILjava.lang.Object;)" );
  private static final com.objectspace.voyager.util.Token __class3 = new com.objectspace.voyager.util.Token( "<init>(Lcom.objectspace.jgl.SList;)" );
  private static final com.objectspace.voyager.util.Token __instance0 = new com.objectspace.voyager.util.Token( "clone()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance1 = new com.objectspace.voyager.util.Token( "equals(Lcom.objectspace.jgl.SList;)Z" );
  private static final com.objectspace.voyager.util.Token __instance2 = new com.objectspace.voyager.util.Token( "toString()Ljava.lang.String;" );
  private static final com.objectspace.voyager.util.Token __instance3 = new com.objectspace.voyager.util.Token( "begin()Lcom.objectspace.jgl.SListIterator;" );
  private static final com.objectspace.voyager.util.Token __instance4 = new com.objectspace.voyager.util.Token( "end()Lcom.objectspace.jgl.SListIterator;" );
  private static final com.objectspace.voyager.util.Token __instance5 = new com.objectspace.voyager.util.Token( "elements()Ljava.util.Enumeration;" );
  private static final com.objectspace.voyager.util.Token __instance6 = new com.objectspace.voyager.util.Token( "start()Lcom.objectspace.jgl.ForwardIterator;" );
  private static final com.objectspace.voyager.util.Token __instance7 = new com.objectspace.voyager.util.Token( "finish()Lcom.objectspace.jgl.ForwardIterator;" );
  private static final com.objectspace.voyager.util.Token __instance8 = new com.objectspace.voyager.util.Token( "copy(Lcom.objectspace.jgl.SList;)V" );
  private static final com.objectspace.voyager.util.Token __instance9 = new com.objectspace.voyager.util.Token( "isEmpty()Z" );
  private static final com.objectspace.voyager.util.Token __instance10 = new com.objectspace.voyager.util.Token( "size()I" );
  private static final com.objectspace.voyager.util.Token __instance11 = new com.objectspace.voyager.util.Token( "maxSize()I" );
  private static final com.objectspace.voyager.util.Token __instance12 = new com.objectspace.voyager.util.Token( "at(I)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance13 = new com.objectspace.voyager.util.Token( "put(ILjava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance14 = new com.objectspace.voyager.util.Token( "insert(Lcom.objectspace.jgl.SListIterator;Ljava.lang.Object;)Lcom.objectspace.jgl.SListIterator;" );
  private static final com.objectspace.voyager.util.Token __instance15 = new com.objectspace.voyager.util.Token( "insert(ILjava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance16 = new com.objectspace.voyager.util.Token( "insert(Lcom.objectspace.jgl.SListIterator;ILjava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance17 = new com.objectspace.voyager.util.Token( "insert(IILjava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance18 = new com.objectspace.voyager.util.Token( "insert(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.InputIterator;Lcom.objectspace.jgl.InputIterator;)V" );
  private static final com.objectspace.voyager.util.Token __instance19 = new com.objectspace.voyager.util.Token( "back()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance20 = new com.objectspace.voyager.util.Token( "front()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance21 = new com.objectspace.voyager.util.Token( "clear()V" );
  private static final com.objectspace.voyager.util.Token __instance22 = new com.objectspace.voyager.util.Token( "popBack()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance23 = new com.objectspace.voyager.util.Token( "pushFront(Ljava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance24 = new com.objectspace.voyager.util.Token( "popFront()Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance25 = new com.objectspace.voyager.util.Token( "add(Ljava.lang.Object;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance26 = new com.objectspace.voyager.util.Token( "pushBack(Ljava.lang.Object;)V" );
  private static final com.objectspace.voyager.util.Token __instance27 = new com.objectspace.voyager.util.Token( "swap(Lcom.objectspace.jgl.SList;)V" );
  private static final com.objectspace.voyager.util.Token __instance28 = new com.objectspace.voyager.util.Token( "remove(Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance29 = new com.objectspace.voyager.util.Token( "remove(Ljava.lang.Object;I)I" );
  private static final com.objectspace.voyager.util.Token __instance30 = new com.objectspace.voyager.util.Token( "remove(Ljava.util.Enumeration;Ljava.util.Enumeration;Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance31 = new com.objectspace.voyager.util.Token( "remove(IILjava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance32 = new com.objectspace.voyager.util.Token( "replace(Ljava.lang.Object;Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance33 = new com.objectspace.voyager.util.Token( "replace(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SListIterator;Ljava.lang.Object;Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance34 = new com.objectspace.voyager.util.Token( "replace(IILjava.lang.Object;Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance35 = new com.objectspace.voyager.util.Token( "count(Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance36 = new com.objectspace.voyager.util.Token( "count(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SListIterator;Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance37 = new com.objectspace.voyager.util.Token( "count(IILjava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance38 = new com.objectspace.voyager.util.Token( "find(Ljava.lang.Object;)Lcom.objectspace.jgl.SListIterator;" );
  private static final com.objectspace.voyager.util.Token __instance39 = new com.objectspace.voyager.util.Token( "indexOf(Ljava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance40 = new com.objectspace.voyager.util.Token( "find(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SListIterator;Ljava.lang.Object;)Lcom.objectspace.jgl.SListIterator;" );
  private static final com.objectspace.voyager.util.Token __instance41 = new com.objectspace.voyager.util.Token( "indexOf(IILjava.lang.Object;)I" );
  private static final com.objectspace.voyager.util.Token __instance42 = new com.objectspace.voyager.util.Token( "contains(Ljava.lang.Object;)Z" );
  private static final com.objectspace.voyager.util.Token __instance43 = new com.objectspace.voyager.util.Token( "remove(Ljava.util.Enumeration;)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance44 = new com.objectspace.voyager.util.Token( "remove(I)Ljava.lang.Object;" );
  private static final com.objectspace.voyager.util.Token __instance45 = new com.objectspace.voyager.util.Token( "remove(Ljava.util.Enumeration;Ljava.util.Enumeration;)I" );
  private static final com.objectspace.voyager.util.Token __instance46 = new com.objectspace.voyager.util.Token( "remove(II)I" );
  private static final com.objectspace.voyager.util.Token __instance47 = new com.objectspace.voyager.util.Token( "splice(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SList;)V" );
  private static final com.objectspace.voyager.util.Token __instance48 = new com.objectspace.voyager.util.Token( "splice(ILcom.objectspace.jgl.SList;)V" );
  private static final com.objectspace.voyager.util.Token __instance49 = new com.objectspace.voyager.util.Token( "splice(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SList;Lcom.objectspace.jgl.SListIterator;)V" );
  private static final com.objectspace.voyager.util.Token __instance50 = new com.objectspace.voyager.util.Token( "splice(ILcom.objectspace.jgl.SList;I)V" );
  private static final com.objectspace.voyager.util.Token __instance51 = new com.objectspace.voyager.util.Token( "splice(Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SList;Lcom.objectspace.jgl.SListIterator;Lcom.objectspace.jgl.SListIterator;)V" );
  private static final com.objectspace.voyager.util.Token __instance52 = new com.objectspace.voyager.util.Token( "splice(ILcom.objectspace.jgl.SList;II)V" );
  
  static
    {
    __register( new VSList() );
    }
  
  /**
   * Called to force static registration.
   */
  protected void __register()
    {
    }
  
  /**
   * Construct a VSList that is not associated with an object.
   * This function is used internally by Voyager and should not
   * be invoked by user code. Any attempt to send a message to a
   * reference created using this default constructor will cause a
   * NullPointerException to be thrown.
   */
  public VSList()
    {
    }
  
  public String getOriginalClassName()
    {
    return "com.objectspace.jgl.SList";
    }
  
  public boolean originalIsInterface()
    {
    return false;
    }
  
  /**
   * Construct a VSList and connect it to the specified object.
   * @param reference A reference to the object to connect to.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( com.objectspace.voyager.space.VSubspace reference ) throws com.objectspace.voyager.VoyagerException
    {
    __connectTo( reference );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __constructor( __address, __classname, __messenger, __class0, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( int arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeInt( arg1 );
    __constructor( __address, __classname, __messenger, __class1, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( int arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( int arg1, Object arg2, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    __constructor( __address, __classname, __messenger, __class2, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( int arg1, Object arg2, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, arg2, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @param __timeout The timeout value in milliseconds.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( com.objectspace.jgl.SList arg1, String __address, long __timeout ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Messenger __messenger = __newConstructorDefaultMessenger();
    __messenger.writeObject( arg1 );
    __constructor( __address, __classname, __messenger, __class3, __timeout );
    }
  
    /**
   * @param __address The address of the program where the instantiation should occur.
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public VSList( com.objectspace.jgl.SList arg1, String __address ) throws com.objectspace.voyager.VoyagerException
    {
    this( arg1, __address, __DEFAULT_TIMEOUT );
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result clone( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance0 );
    }
  
  
  public Object clone()
    {
    com.objectspace.voyager.message.Result __result = clone( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result equals( com.objectspace.jgl.SList arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance1 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public boolean equals( com.objectspace.jgl.SList arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = equals( arg1, __newDefaultMessenger() );
    return __result.readBoolean();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result toString( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance2 );
    }
  
  
  public String toString()
    {
    com.objectspace.voyager.message.Result __result = toString( __newDefaultMessenger() );
    return (String) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result begin( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance3 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.SListIterator begin() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = begin( __newDefaultMessenger() );
    return (com.objectspace.jgl.SListIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result end( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance4 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.SListIterator end() throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = end( __newDefaultMessenger() );
    return (com.objectspace.jgl.SListIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result elements( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance5 );
    }
  
  
  public java.util.Enumeration elements()
    {
    com.objectspace.voyager.message.Result __result = elements( __newDefaultMessenger() );
    return (java.util.Enumeration) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result start( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance6 );
    }
  
  
  public com.objectspace.jgl.ForwardIterator start()
    {
    com.objectspace.voyager.message.Result __result = start( __newDefaultMessenger() );
    return (com.objectspace.jgl.ForwardIterator) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result finish( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance7 );
    }
  
  
  public com.objectspace.jgl.ForwardIterator finish()
    {
    com.objectspace.voyager.message.Result __result = finish( __newDefaultMessenger() );
    return (com.objectspace.jgl.ForwardIterator) __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result copy( com.objectspace.jgl.SList arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance8 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void copy( com.objectspace.jgl.SList arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = copy( arg1, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result isEmpty( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance9 );
    }
  
  
  public boolean isEmpty()
    {
    com.objectspace.voyager.message.Result __result = isEmpty( __newDefaultMessenger() );
    return __result.readBooleanRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result size( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance10 );
    }
  
  
  public int size()
    {
    com.objectspace.voyager.message.Result __result = size( __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result maxSize( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance11 );
    }
  
  
  public int maxSize()
    {
    com.objectspace.voyager.message.Result __result = maxSize( __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result at( int arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    return __instanceMethod( __messenger, __instance12 );
    }
  
  
  public Object at( int arg1 )
    {
    com.objectspace.voyager.message.Result __result = at( arg1, __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result put( int arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance13 );
    }
  
  
  public void put( int arg1, Object arg2 )
    {
    com.objectspace.voyager.message.Result __result = put( arg1, arg2, __newDefaultMessenger() );
    __result.rethrowExceptionRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result insert( com.objectspace.jgl.SListIterator arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance14 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.SListIterator insert( com.objectspace.jgl.SListIterator arg1, Object arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = insert( arg1, arg2, __newDefaultMessenger() );
    return (com.objectspace.jgl.SListIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result insert( int arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance15 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void insert( int arg1, Object arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = insert( arg1, arg2, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result insert( com.objectspace.jgl.SListIterator arg1, int arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance16 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void insert( com.objectspace.jgl.SListIterator arg1, int arg2, Object arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = insert( arg1, arg2, arg3, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result insert( int arg1, int arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance17 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void insert( int arg1, int arg2, Object arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = insert( arg1, arg2, arg3, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result insert( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance18 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void insert( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.InputIterator arg2, com.objectspace.jgl.InputIterator arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = insert( arg1, arg2, arg3, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result back( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance19 );
    }
  
  
  public Object back()
    {
    com.objectspace.voyager.message.Result __result = back( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result front( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance20 );
    }
  
  
  public Object front()
    {
    com.objectspace.voyager.message.Result __result = front( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result clear( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance21 );
    }
  
  
  public void clear()
    {
    com.objectspace.voyager.message.Result __result = clear( __newDefaultMessenger() );
    __result.rethrowExceptionRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result popBack( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance22 );
    }
  
  
  public Object popBack()
    {
    com.objectspace.voyager.message.Result __result = popBack( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result pushFront( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance23 );
    }
  
  
  public void pushFront( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = pushFront( arg1, __newDefaultMessenger() );
    __result.rethrowExceptionRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result popFront( com.objectspace.voyager.message.Messenger __messenger )
    {
    return __instanceMethod( __messenger, __instance24 );
    }
  
  
  public Object popFront()
    {
    com.objectspace.voyager.message.Result __result = popFront( __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result add( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance25 );
    }
  
  
  public Object add( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = add( arg1, __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result pushBack( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance26 );
    }
  
  
  public void pushBack( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = pushBack( arg1, __newDefaultMessenger() );
    __result.rethrowExceptionRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result swap( com.objectspace.jgl.SList arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance27 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void swap( com.objectspace.jgl.SList arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = swap( arg1, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance28 );
    }
  
  
  public int remove( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( Object arg1, int arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeInt( arg2 );
    return __instanceMethod( __messenger, __instance29 );
    }
  
  
  public int remove( Object arg1, int arg2 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( java.util.Enumeration arg1, java.util.Enumeration arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance30 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int remove( java.util.Enumeration arg1, java.util.Enumeration arg2, Object arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, arg3, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( int arg1, int arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance31 );
    }
  
  
  public int remove( int arg1, int arg2, Object arg3 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, arg3, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result replace( Object arg1, Object arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance32 );
    }
  
  
  public int replace( Object arg1, Object arg2 )
    {
    com.objectspace.voyager.message.Result __result = replace( arg1, arg2, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result replace( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3, Object arg4, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __instanceMethod( __messenger, __instance33 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int replace( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3, Object arg4 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = replace( arg1, arg2, arg3, arg4, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result replace( int arg1, int arg2, Object arg3, Object arg4, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __instanceMethod( __messenger, __instance34 );
    }
  
  
  public int replace( int arg1, int arg2, Object arg3, Object arg4 )
    {
    com.objectspace.voyager.message.Result __result = replace( arg1, arg2, arg3, arg4, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result count( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance35 );
    }
  
  
  public int count( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = count( arg1, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result count( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance36 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int count( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = count( arg1, arg2, arg3, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result count( int arg1, int arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance37 );
    }
  
  
  public int count( int arg1, int arg2, Object arg3 )
    {
    com.objectspace.voyager.message.Result __result = count( arg1, arg2, arg3, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result find( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance38 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.SListIterator find( Object arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = find( arg1, __newDefaultMessenger() );
    return (com.objectspace.jgl.SListIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result indexOf( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance39 );
    }
  
  
  public int indexOf( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = indexOf( arg1, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result find( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance40 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public com.objectspace.jgl.SListIterator find( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SListIterator arg2, Object arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = find( arg1, arg2, arg3, __newDefaultMessenger() );
    return (com.objectspace.jgl.SListIterator) __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result indexOf( int arg1, int arg2, Object arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance41 );
    }
  
  
  public int indexOf( int arg1, int arg2, Object arg3 )
    {
    com.objectspace.voyager.message.Result __result = indexOf( arg1, arg2, arg3, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result contains( Object arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance42 );
    }
  
  
  public boolean contains( Object arg1 )
    {
    com.objectspace.voyager.message.Result __result = contains( arg1, __newDefaultMessenger() );
    return __result.readBooleanRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( java.util.Enumeration arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    return __instanceMethod( __messenger, __instance43 );
    }
  
  
  public Object remove( java.util.Enumeration arg1 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, __newDefaultMessenger() );
    return __result.readObjectRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( int arg1, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    return __instanceMethod( __messenger, __instance44 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public Object remove( int arg1 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, __newDefaultMessenger() );
    return __result.readObject();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( java.util.Enumeration arg1, java.util.Enumeration arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance45 );
    }
  
  
  public int remove( java.util.Enumeration arg1, java.util.Enumeration arg2 )
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, __newDefaultMessenger() );
    return __result.readIntRuntime();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result remove( int arg1, int arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeInt( arg2 );
    return __instanceMethod( __messenger, __instance46 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public int remove( int arg1, int arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = remove( arg1, arg2, __newDefaultMessenger() );
    return __result.readInt();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance47 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( int arg1, com.objectspace.jgl.SList arg2, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    return __instanceMethod( __messenger, __instance48 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( int arg1, com.objectspace.jgl.SList arg2 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2, com.objectspace.jgl.SListIterator arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    return __instanceMethod( __messenger, __instance49 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2, com.objectspace.jgl.SListIterator arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, arg3, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( int arg1, com.objectspace.jgl.SList arg2, int arg3, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeInt( arg3 );
    return __instanceMethod( __messenger, __instance50 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( int arg1, com.objectspace.jgl.SList arg2, int arg3 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, arg3, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2, com.objectspace.jgl.SListIterator arg3, com.objectspace.jgl.SListIterator arg4, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeObject( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeObject( arg3 );
    __messenger.writeObject( arg4 );
    return __instanceMethod( __messenger, __instance51 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( com.objectspace.jgl.SListIterator arg1, com.objectspace.jgl.SList arg2, com.objectspace.jgl.SListIterator arg3, com.objectspace.jgl.SListIterator arg4 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, arg3, arg4, __newDefaultMessenger() );
    __result.rethrowException();
    }
  
    /**
   * @param __messenger The messenger that should be used to invoke the method
   */
  public com.objectspace.voyager.message.Result splice( int arg1, com.objectspace.jgl.SList arg2, int arg3, int arg4, com.objectspace.voyager.message.Messenger __messenger )
    {
    __messenger.writeInt( arg1 );
    __messenger.writeObject( arg2 );
    __messenger.writeInt( arg3 );
    __messenger.writeInt( arg4 );
    return __instanceMethod( __messenger, __instance52 );
    }
  
    /**
   * @exception com.objectspace.voyager.VoyagerException A voyager-related exception occurred.
   */
  public void splice( int arg1, com.objectspace.jgl.SList arg2, int arg3, int arg4 ) throws com.objectspace.voyager.VoyagerException
    {
    com.objectspace.voyager.message.Result __result = splice( arg1, arg2, arg3, arg4, __newDefaultMessenger() );
    __result.rethrowException();
    }
  }
